name: cs7643-a3-nlp
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.10
  - pytorch
  - pytorch-cuda=11.7
  - torchvision
  - torchaudio
  - matplotlib
  - tqdm
  - jupyter
  - pip
  - pip:
      - notebook
      - numpy
