data:
  test_size: 0.15
  val_size: 0.15
  salary_classes: 3

train:
  batch_size: 64
  head_lr: 0.001
  lm_lr: 0.00002
  n_epochs: 3
  head_phase_epochs: 1
  num_workers: 4
  seed: 42
  max_length: 256
  weight_decay: 0.01

network:
  model: bert_fusion
  pretrained_model_name: bert-base-uncased # options: bert-base, bert-large, distilbert-base, bert-base-uncased,  bert-large-uncased, distilbert-base-uncased
  hidden_dim: 40
  structured_embedding_dim: 64
  freeze_bert: false
  fusion_strategy: cross_attention  # options: concat or cross_attention

optimizer:
  type: adamw # adamw or sgd
  weight_decay: 0.01
  betas: [ 0.9, 0.999 ] # only for adamw
  momentum: 0.9 # only for sgd